// Mock data — Dashboard Socio MLM
// Mannatech Demo Premium | DMLABS

export const mockSocio = {
  perfil: {
    id: "ASC-1542",
    nombre: "Carlos Mendoza Rivera",
    email: "carlos.mendoza@email.com",
    telefono: "+52 33 5678 1234",
    rango: "Asociado Plata",
    rangoSiguiente: "Asociado Oro",
    fechaIngreso: "2023-01-20",
    avatar: null,
  },

  kpis: {
    ventasMes: 45800,
    pvPersonal: 12800,
    pvGrupal: 38500,
    clientesActivos: 8,
    metaMensual: 55000,
    comisionesEsteMes: 4250,
    nuevosMiembros: 2,
  },

  ventasHistorial: [
    { mes: "Enero 2026", ventas: 32400, pv: 8200 },
    { mes: "Febrero 2026", ventas: 38900, pv: 9800 },
    { mes: "Marzo 2026", ventas: 41200, pv: 10500 },
    { mes: "Abril 2026", ventas: 36700, pv: 9100 },
    { mes: "Mayo 2026", ventas: 43500, pv: 11200 },
    { mes: "Junio 2026", ventas: 45800, pv: 12800 },
  ],

  red: [
    // Nivel 1 — directos de Carlos (patrocinadorId: null)
    {
      id: "ASC-2001",
      nombre: "Ana Lucia Fernandez",
      nivel: 1 as const,
      rango: "Asociado Bronce",
      pvPersonal: 4200,
      pvGrupal: 8900,
      activo: true,
      avatar: null,
      patrocinadorId: null,
      fechaIngreso: "2023-06-10",
    },
    {
      id: "ASC-2002",
      nombre: "Roberto Jimenez Soto",
      nivel: 1 as const,
      rango: "Asociado Bronce",
      pvPersonal: 3800,
      pvGrupal: 6200,
      activo: true,
      avatar: null,
      patrocinadorId: null,
      fechaIngreso: "2023-08-22",
    },
    {
      id: "ASC-2003",
      nombre: "Laura Patricia Gomez",
      nivel: 1 as const,
      rango: "Asociado",
      pvPersonal: 2100,
      pvGrupal: 2100,
      activo: true,
      avatar: null,
      patrocinadorId: null,
      fechaIngreso: "2024-01-15",
    },
    {
      id: "ASC-2004",
      nombre: "Miguel Angel Torres",
      nivel: 1 as const,
      rango: "Asociado",
      pvPersonal: 1500,
      pvGrupal: 1500,
      activo: false,
      avatar: null,
      patrocinadorId: null,
      fechaIngreso: "2024-03-08",
    },
    {
      id: "ASC-2005",
      nombre: "Sofia Ramirez Valdez",
      nivel: 1 as const,
      rango: "Asociado Bronce",
      pvPersonal: 3200,
      pvGrupal: 5800,
      activo: true,
      avatar: null,
      patrocinadorId: null,
      fechaIngreso: "2024-05-20",
    },
    // Nivel 2 — bajo Ana Lucia
    {
      id: "ASC-3001",
      nombre: "Daniela Herrera Cruz",
      nivel: 2 as const,
      rango: "Asociado",
      pvPersonal: 1800,
      pvGrupal: 1800,
      activo: true,
      avatar: null,
      patrocinadorId: "ASC-2001",
      fechaIngreso: "2024-02-14",
    },
    {
      id: "ASC-3002",
      nombre: "Fernando Castillo Ruiz",
      nivel: 2 as const,
      rango: "Asociado",
      pvPersonal: 2900,
      pvGrupal: 2900,
      activo: true,
      avatar: null,
      patrocinadorId: "ASC-2001",
      fechaIngreso: "2024-04-30",
    },
    // Nivel 2 — bajo Roberto
    {
      id: "ASC-3003",
      nombre: "Gabriela Morales Luna",
      nivel: 2 as const,
      rango: "Asociado",
      pvPersonal: 1200,
      pvGrupal: 1200,
      activo: true,
      avatar: null,
      patrocinadorId: "ASC-2002",
      fechaIngreso: "2024-06-12",
    },
    {
      id: "ASC-3004",
      nombre: "Jose Luis Navarro",
      nivel: 2 as const,
      rango: "Asociado",
      pvPersonal: 1200,
      pvGrupal: 1200,
      activo: false,
      avatar: null,
      patrocinadorId: "ASC-2002",
      fechaIngreso: "2024-07-05",
    },
    // Nivel 2 — bajo Sofia
    {
      id: "ASC-3005",
      nombre: "Alejandra Diaz Ortega",
      nivel: 2 as const,
      rango: "Asociado",
      pvPersonal: 2600,
      pvGrupal: 2600,
      activo: true,
      avatar: null,
      patrocinadorId: "ASC-2005",
      fechaIngreso: "2025-01-18",
    },
    // Nivel 3 — bajo Daniela
    {
      id: "ASC-4001",
      nombre: "Paola Rios Sandoval",
      nivel: 3 as const,
      rango: "Asociado",
      pvPersonal: 900,
      pvGrupal: 900,
      activo: true,
      avatar: null,
      patrocinadorId: "ASC-3001",
      fechaIngreso: "2025-03-22",
    },
    // Nivel 3 — bajo Fernando
    {
      id: "ASC-4002",
      nombre: "Ricardo Vazquez Pena",
      nivel: 3 as const,
      rango: "Asociado",
      pvPersonal: 1100,
      pvGrupal: 1100,
      activo: true,
      avatar: null,
      patrocinadorId: "ASC-3002",
      fechaIngreso: "2025-05-10",
    },
    {
      id: "ASC-4003",
      nombre: "Monica Estrada Leon",
      nivel: 3 as const,
      rango: "Asociado",
      pvPersonal: 800,
      pvGrupal: 800,
      activo: true,
      avatar: null,
      patrocinadorId: "ASC-3002",
      fechaIngreso: "2025-06-01",
    },
    // Nivel 3 — bajo Alejandra
    {
      id: "ASC-4004",
      nombre: "Ivan Delgado Fuentes",
      nivel: 3 as const,
      rango: "Asociado",
      pvPersonal: 700,
      pvGrupal: 700,
      activo: true,
      avatar: null,
      patrocinadorId: "ASC-3005",
      fechaIngreso: "2025-08-14",
    },
    {
      id: "ASC-4005",
      nombre: "Veronica Salinas Mora",
      nivel: 3 as const,
      rango: "Asociado",
      pvPersonal: 600,
      pvGrupal: 600,
      activo: false,
      avatar: null,
      patrocinadorId: "ASC-3005",
      fechaIngreso: "2025-09-20",
    },
  ],

  clientes: [
    {
      id: "CLI-3001",
      nombre: "Maria Garcia Lopez",
      email: "maria.garcia@email.com",
      ultimaCompra: "2026-06-28",
      totalCompras: 18750,
      estatus: "activo" as const,
      productosFavoritos: ["Ambrotose", "MannaBears"],
    },
    {
      id: "CLI-3002",
      nombre: "Pedro Sanchez Ruiz",
      email: "pedro.sanchez@email.com",
      ultimaCompra: "2026-06-20",
      totalCompras: 12400,
      estatus: "activo" as const,
      productosFavoritos: ["GI-Pro", "Plus"],
    },
    {
      id: "CLI-3003",
      nombre: "Elena Vargas Torres",
      email: "elena.vargas@email.com",
      ultimaCompra: "2026-06-15",
      totalCompras: 9800,
      estatus: "activo" as const,
      productosFavoritos: ["Optimal Support Packets"],
    },
    {
      id: "CLI-3004",
      nombre: "Javier Hernandez Diaz",
      email: "javier.hdz@email.com",
      ultimaCompra: "2026-06-10",
      totalCompras: 15200,
      estatus: "activo" as const,
      productosFavoritos: ["Ambrotose", "PhytoMatrix"],
    },
    {
      id: "CLI-3005",
      nombre: "Carmen Ortiz Luna",
      email: "carmen.ortiz@email.com",
      ultimaCompra: "2026-05-28",
      totalCompras: 7600,
      estatus: "activo" as const,
      productosFavoritos: ["MannaBears", "GI-Pro"],
    },
    {
      id: "CLI-3006",
      nombre: "Luis Alberto Mendez",
      email: "luis.mendez@email.com",
      ultimaCompra: "2026-05-12",
      totalCompras: 4300,
      estatus: "activo" as const,
      productosFavoritos: ["Plus"],
    },
    {
      id: "CLI-3007",
      nombre: "Rosa Martinez Aguilar",
      email: "rosa.mtz@email.com",
      ultimaCompra: "2026-04-05",
      totalCompras: 3200,
      estatus: "inactivo" as const,
      productosFavoritos: ["Ambrotose"],
    },
    {
      id: "CLI-3008",
      nombre: "Arturo Dominguez Vega",
      email: "arturo.dom@email.com",
      ultimaCompra: "2026-03-18",
      totalCompras: 2100,
      estatus: "inactivo" as const,
      productosFavoritos: ["PhytoMatrix", "MannaBears"],
    },
  ],

  comisiones: {
    total: 4250,
    desglose: [
      { tipo: "Bono Retail", monto: 1800 },
      { tipo: "Bono Grupal", monto: 1650 },
      { tipo: "Bono Liderazgo", monto: 800 },
    ],
    historial: [
      { mes: "Enero 2026", monto: 2800, tipo: "Bono Retail" },
      { mes: "Febrero 2026", monto: 3100, tipo: "Bono Grupal" },
      { mes: "Marzo 2026", monto: 3450, tipo: "Bono Retail" },
      { mes: "Abril 2026", monto: 3200, tipo: "Bono Liderazgo" },
      { mes: "Mayo 2026", monto: 3800, tipo: "Bono Grupal" },
      { mes: "Junio 2026", monto: 4250, tipo: "Bono Retail" },
    ],
  },

  pedidos: [
    {
      id: "ORD-S-501",
      fecha: "2026-06-28",
      cliente: "Maria Garcia Lopez",
      tipo: "cliente" as const,
      items: [
        { nombre: "Ambrotose", cantidad: 2, precio: 1850 },
        { nombre: "MannaBears", cantidad: 1, precio: 780 },
      ],
      total: 4629,
      estatus: "en camino",
    },
    {
      id: "ORD-S-498",
      fecha: "2026-06-22",
      cliente: "Pedro Sanchez Ruiz",
      tipo: "cliente" as const,
      items: [
        { nombre: "GI-Pro", cantidad: 1, precio: 1680 },
      ],
      total: 1829,
      estatus: "entregado",
    },
    {
      id: "ORD-S-490",
      fecha: "2026-06-15",
      cliente: "Carlos Mendoza Rivera",
      tipo: "personal" as const,
      items: [
        { nombre: "Ambrotose", cantidad: 3, precio: 1850 },
        { nombre: "Plus", cantidad: 2, precio: 1450 },
      ],
      total: 8450,
      estatus: "entregado",
    },
    {
      id: "ORD-S-482",
      fecha: "2026-06-05",
      cliente: "Elena Vargas Torres",
      tipo: "cliente" as const,
      items: [
        { nombre: "Optimal Support Packets", cantidad: 1, precio: 2350 },
      ],
      total: 2499,
      estatus: "entregado",
    },
    {
      id: "ORD-S-475",
      fecha: "2026-05-28",
      cliente: "Carmen Ortiz Luna",
      tipo: "cliente" as const,
      items: [
        { nombre: "MannaBears", cantidad: 2, precio: 780 },
        { nombre: "GI-Pro", cantidad: 1, precio: 1680 },
      ],
      total: 3389,
      estatus: "entregado",
    },
  ],

  herramientas: {
    linkReferido: "https://mannatech.com/ref/ASC-1542",
    materialesDescargables: [
      { nombre: "Catalogo de Productos 2026", tipo: "PDF", tamano: "4.2 MB" },
      { nombre: "Presentacion Plan de Negocio", tipo: "PPTX", tamano: "8.7 MB" },
      { nombre: "Guia de Inicio Rapido", tipo: "PDF", tamano: "1.8 MB" },
      { nombre: "Banners para Redes Sociales", tipo: "ZIP", tamano: "12.3 MB" },
      { nombre: "Video Testimonios Clientes", tipo: "MP4", tamano: "45.0 MB" },
    ],
    qrCode: "ASC-1542",
  },

  calendario: [
    {
      id: 1,
      titulo: "Webinar: Nuevos Productos Q3",
      fecha: "2026-07-05",
      hora: "19:00",
      tipo: "webinar" as const,
      descripcion: "Presentacion de la nueva linea de productos del tercer trimestre",
      enlace: "https://zoom.us/j/123456789",
    },
    {
      id: 2,
      titulo: "Entrenamiento de Ventas",
      fecha: "2026-07-10",
      hora: "10:00",
      tipo: "entrenamiento" as const,
      descripcion: "Tecnicas avanzadas para cerrar ventas y manejar objeciones",
      enlace: "https://zoom.us/j/987654321",
    },
    {
      id: 3,
      titulo: "Reunion Regional Guadalajara",
      fecha: "2026-07-15",
      hora: "18:00",
      tipo: "evento" as const,
      descripcion: "Encuentro presencial con lideres de la region occidente en Hotel Hilton",
    },
    {
      id: 4,
      titulo: "Webinar: Ciencia de los Gliconutrientes",
      fecha: "2026-07-20",
      hora: "20:00",
      tipo: "webinar" as const,
      descripcion: "Dr. Steve Nugent explica la tecnologia Ambrotose",
      enlace: "https://zoom.us/j/456789123",
    },
    {
      id: 5,
      titulo: "Convencion Nacional Mannatech Mexico",
      fecha: "2026-08-02",
      hora: "09:00",
      tipo: "evento" as const,
      descripcion: "Evento anual en CDMX — Centro Citibanamex. Incluye reconocimientos y lanzamientos",
    },
  ],

  rango: {
    actual: "Asociado Plata",
    siguiente: "Asociado Oro",
    progreso: 72,
    requisitos: [
      { nombre: "PV Personal", actual: 12800, requerido: 15000, cumplido: false },
      { nombre: "PV Grupal", actual: 38500, requerido: 45000, cumplido: false },
      { nombre: "Asociados Activos Nivel 1", actual: 4, requerido: 5, cumplido: false },
      { nombre: "Meses Consecutivos Calificado", actual: 4, requerido: 3, cumplido: true },
    ],
  },

  aprendizaje: {
    cursosEnProgreso: [
      {
        id: 1,
        titulo: "Fundamentos de la Gliconutricion",
        progreso: 65,
        duracion: "2 horas",
        modulos: 8,
      },
      {
        id: 2,
        titulo: "Liderazgo y Construccion de Equipo",
        progreso: 30,
        duracion: "3 horas",
        modulos: 12,
      },
    ],
    cursosCompletados: [
      { id: 3, titulo: "Introduccion a Mannatech", fechaCompletado: "2023-02-15" },
      { id: 4, titulo: "Conoce tus Productos", fechaCompletado: "2023-04-20" },
      { id: 5, titulo: "Tecnicas de Prospeccion", fechaCompletado: "2024-01-10" },
    ],
  },

  notificaciones: [
    { id: 1, titulo: "Nuevo cliente registrado", descripcion: "Maria Garcia se registro con tu enlace de referido", tiempo: "Hace 3 horas", leida: false },
    { id: 2, titulo: "Comision acreditada", descripcion: "Se acreditaron $1,800 MXN por Bono Retail de junio", tiempo: "Hace 1 dia", leida: false },
    { id: 3, titulo: "Progreso de rango", descripcion: "Estas al 72% de alcanzar Asociado Oro. Sigue asi!", tiempo: "Hace 2 dias", leida: false },
    { id: 4, titulo: "Recordatorio de evento", descripcion: "El webinar 'Nuevos Productos Q3' es el 5 de julio a las 7pm", tiempo: "Hace 3 dias", leida: true },
    { id: 5, titulo: "Meta mensual", descripcion: "Llevas $45,800 de tu meta de $55,000 este mes", tiempo: "Hace 5 dias", leida: true },
  ],
} as const
